<?php

namespace ShoppingCartBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * DiscountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllDateDisc()
    {
        return $this->createQueryBuilder('d')
            ->innerJoin('d.products', 'p', Join::WITH, 'd.product_id = p.id')
            ->innerJoin('d.categories', 'c', Join::WITH, 'd.category_id = c.id')
            ->orderBy('d.endDate')
            //->orderBy('d.percent')
            ->getQuery()
            ->getResult();
    }
}
