<?php

namespace ShoppingCartBundle\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\Query\Expr\Join;
use ShoppingCartBundle\Entity\Payment;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends \Doctrine\ORM\EntityRepository
{

    public function __construct(EntityManager $em, Mapping\ClassMetadata $class = null)
    {
        parent::__construct($em,
            $class == null ? new Mapping\ClassMetadata(Payment::class) : $class
        );
    }

    /**
     * @param $paymentId
     * @param $discount
     * @param $payment
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function paymentPaid($paymentId, $discount, $payment)
    {
        return $this->createQueryBuilder('p')
            ->update()
            ->set('p.payment', '?1')
            ->setParameter(1, $discount)
            ->set('p.payment', '?2')
            ->setParameter(2, $payment)
            ->set('p.isPaid', '?3')
            ->setParameter(3, true)
            ->where('p.id = ?4')
            ->setParameter(4, $paymentId)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findYourCart($userId)
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('p.products', 'pr', Join::WITH, 'pr.id = p.productId')
            ->innerJoin('p.users', 'u', Join::WITH, 'u.id = p.userId')
            ->where('p.userId = :userId')
            ->andWhere('p.isPaid = :isPaid')
            ->orderBy('p.datePurchases')
            ->orderBy('p.id')
            ->setParameter('userId', $userId)
            ->setParameter('isPaid', false)
            ->getQuery()
            ->getResult();
    }

    public function findSumYourCart($userId)
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('p.products', 'pr', Join::WITH, 'pr.id = p.productId')
            ->innerJoin('p.users', 'u', Join::WITH, 'u.id = p.userId')
            ->where('p.userId = :userId')
            ->andWhere('p.isPaid = :isPaid')
            ->orderBy('p.datePurchases')
            ->orderBy('p.id')
            ->setParameter('userId', $userId)
            ->setParameter('isPaid', false)
            ->select('SUM(p.price) AS totalPrice')
            ->getQuery()
            ->getResult();
    }

    public function findSumPayments($userId)
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('p.products', 'pr', Join::WITH, 'pr.id = p.productId')
            ->innerJoin('p.users', 'u', Join::WITH, 'u.id = p.userId')
            ->where('p.userId = :userId')
            ->andWhere('p.isPaid = :isPaid')
            ->orderBy('p.datePurchases')
            ->orderBy('p.id')
            ->setParameter('userId', $userId)
            ->setParameter('isPaid', true)
            ->select('SUM(p.price) AS totalPrice')
            ->getQuery()
            ->getResult();
    }

    public function findAllBuy($userId)
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('p.products', 'pr', Join::WITH, 'pr.id = p.productId')
            ->innerJoin('p.users', 'u', Join::WITH, 'u.id = p.userId')
            ->innerJoin('p.documents', 'd', Join::WITH, 'd.id = p.documentId')
            ->where('p.userId = :userId')
            ->andWhere('p.isPaid = :isPaid')
            ->andWhere('d.isBuy = :isBuy')
            ->orderBy('d.id', 'DESC')
            ->orderBy('p.datePurchases', 'DESC')
            ->setParameter('userId', $userId)
            ->setParameter('isPaid', true)
            ->setParameter('isBuy', true)
            ->getQuery()
            ->getResult();
    }

    public function findAllSales($userId)
    {
        return $this->createQueryBuilder('p')
            ->innerJoin('p.products', 'pr', Join::WITH, 'pr.id = p.productId')
            ->innerJoin('p.users', 'u', Join::WITH, 'u.id = p.userId')
            ->innerJoin('p.documents', 'd', Join::WITH, 'd.id = p.documentId')
            ->where('p.userId = :userId')
            ->andWhere('p.isPaid = :isPaid')
            ->andWhere('d.isSale = :isSale')
            ->orderBy('d.id', 'DESC')
            ->orderBy('p.datePurchases', 'DESC')
            ->setParameter('userId', $userId)
            ->setParameter('isPaid', true)
            ->setParameter('isSale', true)
            ->getQuery()
            ->getResult();
    }

    public function updateQttyPayment($paymentId, $qtyy)
    {
        return $this->createQueryBuilder('p')
            ->update()
            ->set('p.qtty', '?1')
            ->setParameter(1, $qtyy)
            ->where('p.id = ?2')
            ->setParameter(2, $paymentId)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
