<?php

namespace ShoppingCartBundle\Repository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
    public function changeRole($roleId, $userId)
    {
        $query = 'UPDATE users_roles SET role_id = :roleId WHERE user_id = :userId';
        $params = array('roleId' => $roleId, 'userId' => $userId);

        return $this->getEntityManager()->getConnection()
            ->executeQuery($query, $params)->execute();
    }
}
