<?php

namespace ShoppingCartBundle\Repository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;
use ShoppingCartBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManager $em, Mapping\ClassMetadata $class = null)
    {
        parent::__construct($em,
            $class == null ? new Mapping\ClassMetadata(User::class) : $class
        );
    }

    public function banUserBool($isBan, $userId)
    {
        $query = 'UPDATE users SET is_ban = :isBan WHERE id = :userId';
        $params = array('isBan' => $isBan, 'userId' => $userId);

        return $this->getEntityManager()
            ->getConnection()
            ->executeQuery($query, $params)
            ->execute();
    }

    public function setEntityManager()
    {
    }
}
