<?php

namespace ShoppingCartBundle\Repository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;
use ShoppingCartBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManager $em, Mapping\ClassMetadata $class = null)
    {
        parent::__construct($em,
            $class == null ? new Mapping\ClassMetadata(User::class) : $class
        );
    }

    public function updateBanUser(int $userId, bool $isBan)
    {
        return $this->createQueryBuilder('u')
            ->update()
            ->set('u.isBan', '?1')
            ->setParameter(1, $isBan)
            ->where('u.id = ?2')
            ->setParameter(2, $userId)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function updateCash(int $userId, float $cash)
    {
        return $this->createQueryBuilder('u')
            ->update()
            ->set('u.cash', '?1')
            ->setParameter(1, $cash)
            ->where('u.id = ?2')
            ->setParameter(2, $userId)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
